name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo "Hello User"
        run: |
          echo "Hola CRVC"
      - name: "Say current date"
        run: date
      - run: ls -l
